Added build dir check

diff --git a/.github/workflows/dev-pull-request-checks.yml b/.github/workflows/dev-pull-request-checks.yml
--- a/.github/workflows/dev-pull-request-checks.yml
+++ b/.github/workflows/dev-pull-request-checks.yml
@@ -20,6 +20,15 @@ jobs:
           node-version: 'latest'
           cache: 'npm'
 
+      - name: Check if no build directory exists
+        shell: bash
+        run: |
+          if [[ -e ./build ]]; then
+            echo "ERROR: a build directory was found!"
+            echo "       Please remove the build directory."
+            exit 1
+          fi
+
       - name: Install dependencies
         run: npm install
 
